-- 1. Create the roles table
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Insert the standard roles
INSERT INTO user_roles (role_name) VALUES 
('Administrator'),
('CountryManager'),
('Ads'),
('Events'),
('Expert'),
('Basic')
ON CONFLICT (role_name) DO NOTHING;

-- 3. Enable RLS (Security)
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

-- 4. Allow everyone to read roles (needed for Signup/Login/UI)
CREATE POLICY "Public Read Roles" ON user_roles
    FOR SELECT
    USING (true);

-- 5. Allow only Admins to insert/update/delete (Optional, for now manually managed)
-- (You can add specific admin policies later)

-- 6. Future helper: Updating profiles to use Foreign Key (COMMENTED OUT FOR SAFETY)
-- ALTER TABLE profiles 
-- ADD CONSTRAINT fk_profiles_role FOREIGN KEY (role) REFERENCES user_roles(role_name);
