-- Crear Tablas de Referencia para Migración de Usuarios
-- Fecha: 2026-01-22
-- Descripción: Tablas reutilizables para countries, mining_topics, languages

-- ============================================
-- TABLA 1: countries
-- ============================================
CREATE TABLE IF NOT EXISTS public.countries (
    id SERIAL PRIMARY KEY,
    code VARCHAR(10) UNIQUE,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_countries_name ON public.countries(name);
CREATE INDEX IF NOT EXISTS idx_countries_code ON public.countries(code);

-- Insertar todos los países
INSERT INTO public.countries (code, name, display_name) VALUES
('AF', 'Afghanistan', 'Afghanistan'),
('AX', 'Aland Islands', 'Aland Islands'),
('AL', 'Albania', 'Albania'),
('DZ', 'Algeria', 'Algeria'),
('AS', 'American Samoa', 'American Samoa'),
('AD', 'Andorra', 'Andorra'),
('AO', 'Angola', 'Angola'),
('AI', 'Anguilla', 'Anguilla'),
('AQ', 'Antarctica', 'Antarctica'),
('AG', 'Antigua and Barbuda', 'Antigua and Barbuda'),
('AR', 'Argentina', 'Argentina'),
('AM', 'Armenia', 'Armenia'),
('AW', 'Aruba', 'Aruba'),
('AU', 'Australia', 'Australia'),
('AT', 'Austria', 'Austria'),
('AZ', 'Azerbaijan', 'Azerbaijan'),
('BS', 'Bahamas', 'Bahamas'),
('BH', 'Bahrain', 'Bahrain'),
('BD', 'Bangladesh', 'Bangladesh'),
('BB', 'Barbados', 'Barbados'),
('BY', 'Belarus', 'Belarus'),
('BE', 'Belgium', 'Belgium'),
('BZ', 'Belize', 'Belize'),
('BJ', 'Benin', 'Benin'),
('BM', 'Bermuda', 'Bermuda'),
('BT', 'Bhutan', 'Bhutan'),
('BO', 'Bolivia', 'Bolivia'),
('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
('BW', 'Botswana', 'Botswana'),
('BV', 'Bouvet Island', 'Bouvet Island'),
('BR', 'Brazil', 'Brazil'),
('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory'),
('BN', 'Brunei Darussalam', 'Brunei Darussalam'),
('BG', 'Bulgaria', 'Bulgaria'),
('BF', 'Burkina Faso', 'Burkina Faso'),
('BI', 'Burundi', 'Burundi'),
('KH', 'Cambodia', 'Cambodia'),
('CM', 'Cameroon', 'Cameroon'),
('CA', 'Canada', 'Canada'),
('CV', 'Cape Verde', 'Cape Verde'),
('KY', 'Cayman Islands', 'Cayman Islands'),
('CF', 'Central African Republic', 'Central African Republic'),
('TD', 'Chad', 'Chad'),
('CL', 'Chile', 'Chile'),
('CN', 'China', 'China'),
('CX', 'Christmas Island', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
('CO', 'Colombia', 'Colombia'),
('KM', 'Comoros', 'Comoros'),
('CG', 'Congo', 'Congo'),
('CD', 'Congo, The Democratic Republic of The', 'Congo, The Democratic Republic of The'),
('CK', 'Cook Islands', 'Cook Islands'),
('CR', 'Costa Rica', 'Costa Rica'),
('CI', 'Cote D''Ivoire', 'Cote D''Ivoire'),
('HR', 'Croatia', 'Croatia'),
('CU', 'Cuba', 'Cuba'),
('CY', 'Cyprus', 'Cyprus'),
('CZ', 'Czech Republic', 'Czech Republic'),
('DK', 'Denmark', 'Denmark'),
('DJ', 'Djibouti', 'Djibouti'),
('DM', 'Dominica', 'Dominica'),
('DO', 'Dominican Republic', 'Dominican Republic'),
('EC', 'Ecuador', 'Ecuador'),
('EG', 'Egypt', 'Egypt'),
('SV', 'El Salvador', 'El Salvador'),
('GQ', 'Equatorial Guinea', 'Equatorial Guinea'),
('ER', 'Eritrea', 'Eritrea'),
('EE', 'Estonia', 'Estonia'),
('ET', 'Ethiopia', 'Ethiopia'),
('FK', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'),
('FO', 'Faroe Islands', 'Faroe Islands'),
('FJ', 'Fiji', 'Fiji'),
('FI', 'Finland', 'Finland'),
('FR', 'France', 'France'),
('GF', 'French Guiana', 'French Guiana'),
('PF', 'French Polynesia', 'French Polynesia'),
('TF', 'French Southern Territories', 'French Southern Territories'),
('GA', 'Gabon', 'Gabon'),
('GM', 'Gambia', 'Gambia'),
('GE', 'Georgia', 'Georgia'),
('DE', 'Germany', 'Germany'),
('GH', 'Ghana', 'Ghana'),
('GI', 'Gibraltar', 'Gibraltar'),
('GR', 'Greece', 'Greece'),
('GL', 'Greenland', 'Greenland'),
('GD', 'Grenada', 'Grenada'),
('GP', 'Guadeloupe', 'Guadeloupe'),
('GU', 'Guam', 'Guam'),
('GT', 'Guatemala', 'Guatemala'),
('GG', 'Guernsey', 'Guernsey'),
('GN', 'Guinea', 'Guinea'),
('GW', 'Guinea-Bissau', 'Guinea-Bissau'),
('GY', 'Guyana', 'Guyana'),
('HT', 'Haiti', 'Haiti'),
('HM', 'Heard Island and Mcdonald Islands', 'Heard Island and Mcdonald Islands'),
('VA', 'Holy See (Vatican City State)', 'Holy See (Vatican City State)'),
('HN', 'Honduras', 'Honduras'),
('HK', 'Hong Kong', 'Hong Kong'),
('HU', 'Hungary', 'Hungary'),
('IS', 'Iceland', 'Iceland'),
('IN', 'India', 'India'),
('ID', 'Indonesia', 'Indonesia'),
('IR', 'Iran, Islamic Republic of', 'Iran, Islamic Republic of'),
('IQ', 'Iraq', 'Iraq'),
('IE', 'Ireland', 'Ireland'),
('IM', 'Isle of Man', 'Isle of Man'),
('IL', 'Israel', 'Israel'),
('IT', 'Italy', 'Italy'),
('JM', 'Jamaica', 'Jamaica'),
('JP', 'Japan', 'Japan'),
('JE', 'Jersey', 'Jersey'),
('JO', 'Jordan', 'Jordan'),
('KZ', 'Kazakhstan', 'Kazakhstan'),
('KE', 'Kenya', 'Kenya'),
('KI', 'Kiribati', 'Kiribati'),
('KP', 'Korea, Democratic People''s Republic of', 'Korea, Democratic People''s Republic of'),
('KR', 'Korea, Republic of', 'Korea, Republic of'),
('KW', 'Kuwait', 'Kuwait'),
('KG', 'Kyrgyzstan', 'Kyrgyzstan'),
('LA', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic'),
('LV', 'Latvia', 'Latvia'),
('LB', 'Lebanon', 'Lebanon'),
('LS', 'Lesotho', 'Lesotho'),
('LR', 'Liberia', 'Liberia'),
('LY', 'Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'),
('LI', 'Liechtenstein', 'Liechtenstein'),
('LT', 'Lithuania', 'Lithuania'),
('LU', 'Luxembourg', 'Luxembourg'),
('MO', 'Macao', 'Macao'),
('MK', 'Macedonia, The Former Yugoslav Republic of', 'Macedonia, The Former Yugoslav Republic of'),
('MG', 'Madagascar', 'Madagascar'),
('MW', 'Malawi', 'Malawi'),
('MY', 'Malaysia', 'Malaysia'),
('MV', 'Maldives', 'Maldives'),
('ML', 'Mali', 'Mali'),
('MT', 'Malta', 'Malta'),
('MH', 'Marshall Islands', 'Marshall Islands'),
('MQ', 'Martinique', 'Martinique'),
('MR', 'Mauritania', 'Mauritania'),
('MU', 'Mauritius', 'Mauritius'),
('YT', 'Mayotte', 'Mayotte'),
('MX', 'Mexico', 'Mexico'),
('FM', 'Micronesia, Federated States of', 'Micronesia, Federated States of'),
('MD', 'Moldova, Republic of', 'Moldova, Republic of'),
('MC', 'Monaco', 'Monaco'),
('MN', 'Mongolia', 'Mongolia'),
('ME', 'Montenegro', 'Montenegro'),
('MS', 'Montserrat', 'Montserrat'),
('MA', 'Morocco', 'Morocco'),
('MZ', 'Mozambique', 'Mozambique'),
('MM', 'Myanmar', 'Myanmar'),
('NA', 'Namibia', 'Namibia'),
('NR', 'Nauru', 'Nauru'),
('NP', 'Nepal', 'Nepal'),
('NL', 'Netherlands', 'Netherlands'),
('AN', 'Netherlands Antilles', 'Netherlands Antilles'),
('NC', 'New Caledonia', 'New Caledonia'),
('NZ', 'New Zealand', 'New Zealand'),
('NI', 'Nicaragua', 'Nicaragua'),
('NE', 'Niger', 'Niger'),
('NG', 'Nigeria', 'Nigeria'),
('NU', 'Niue', 'Niue'),
('NF', 'Norfolk Island', 'Norfolk Island'),
('MP', 'Northern Mariana Islands', 'Northern Mariana Islands'),
('NO', 'Norway', 'Norway'),
('OM', 'Oman', 'Oman'),
('PK', 'Pakistan', 'Pakistan'),
('PW', 'Palau', 'Palau'),
('PS', 'Palestinian Territory, Occupied', 'Palestinian Territory, Occupied'),
('PA', 'Panama', 'Panama'),
('PG', 'Papua New Guinea', 'Papua New Guinea'),
('PY', 'Paraguay', 'Paraguay'),
('PE', 'Peru', 'Peru'),
('PH', 'Philippines', 'Philippines'),
('PN', 'Pitcairn', 'Pitcairn'),
('PL', 'Poland', 'Poland'),
('PT', 'Portugal', 'Portugal'),
('PR', 'Puerto Rico', 'Puerto Rico'),
('QA', 'Qatar', 'Qatar'),
('RE', 'Reunion', 'Reunion'),
('RO', 'Romania', 'Romania'),
('RU', 'Russian Federation', 'Russian Federation'),
('RW', 'Rwanda', 'Rwanda'),
('SH', 'Saint Helena', 'Saint Helena'),
('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia', 'Saint Lucia'),
('PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and The Grenadines', 'Saint Vincent and The Grenadines'),
('WS', 'Samoa', 'Samoa'),
('SM', 'San Marino', 'San Marino'),
('ST', 'Sao Tome and Principe', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia', 'Saudi Arabia'),
('SN', 'Senegal', 'Senegal'),
('RS', 'Serbia', 'Serbia'),
('CS', 'Serbia and Montenegro', 'Serbia and Montenegro'),
('SC', 'Seychelles', 'Seychelles'),
('SL', 'Sierra Leone', 'Sierra Leone'),
('SG', 'Singapore', 'Singapore'),
('SK', 'Slovakia', 'Slovakia'),
('SI', 'Slovenia', 'Slovenia'),
('SB', 'Solomon Islands', 'Solomon Islands'),
('SO', 'Somalia', 'Somalia'),
('ZA', 'South Africa', 'South Africa'),
('GS', 'South Georgia and The South Sandwich Islands', 'South Georgia and The South Sandwich Islands'),
('ES', 'Spain', 'Spain'),
('LK', 'Sri Lanka', 'Sri Lanka'),
('SD', 'Sudan', 'Sudan'),
('SR', 'Suriname', 'Suriname'),
('SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
('SZ', 'Swaziland', 'Swaziland'),
('SE', 'Sweden', 'Sweden'),
('CH', 'Switzerland', 'Switzerland'),
('SY', 'Syrian Arab Republic', 'Syrian Arab Republic'),
('TW', 'Taiwan, Province of China', 'Taiwan, Province of China'),
('TJ', 'Tajikistan', 'Tajikistan'),
('TZ', 'Tanzania, United Republic of', 'Tanzania, United Republic of'),
('TH', 'Thailand', 'Thailand'),
('TL', 'Timor-Leste', 'Timor-Leste'),
('TG', 'Togo', 'Togo'),
('TK', 'Tokelau', 'Tokelau'),
('TO', 'Tonga', 'Tonga'),
('TT', 'Trinidad and Tobago', 'Trinidad and Tobago'),
('TN', 'Tunisia', 'Tunisia'),
('TR', 'Turkey', 'Turkey'),
('TM', 'Turkmenistan', 'Turkmenistan'),
('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands'),
('TV', 'Tuvalu', 'Tuvalu'),
('UG', 'Uganda', 'Uganda'),
('UA', 'Ukraine', 'Ukraine'),
('AE', 'United Arab Emirates', 'United Arab Emirates'),
('GB', 'United Kingdom', 'United Kingdom'),
('US', 'United States', 'United States'),
('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands'),
('UY', 'Uruguay', 'Uruguay'),
('UZ', 'Uzbekistan', 'Uzbekistan'),
('VU', 'Vanuatu', 'Vanuatu'),
('VE', 'Venezuela', 'Venezuela'),
('VN', 'Viet Nam', 'Viet Nam'),
('VG', 'Virgin Islands, British', 'Virgin Islands, British'),
('VI', 'Virgin Islands, U.S.', 'Virgin Islands, U.S.'),
('WF', 'Wallis and Futuna', 'Wallis and Futuna'),
('EH', 'Western Sahara', 'Western Sahara'),
('YE', 'Yemen', 'Yemen'),
('ZM', 'Zambia', 'Zambia'),
('ZW', 'Zimbabwe', 'Zimbabwe')
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- TABLA 2: mining_topics (25 topics)
-- ============================================
CREATE TABLE IF NOT EXISTS public.mining_topics (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_mining_topics_slug ON public.mining_topics(slug);
CREATE INDEX IF NOT EXISTS idx_mining_topics_name ON public.mining_topics(name);

-- Insertar los 25 mining topics
INSERT INTO public.mining_topics (slug, name, display_name, order_index) VALUES
('general-mining', '01 General mining', 'General mining', 1),
('mine-preparation', '02 Mine preparation', 'Mine preparation', 2),
('mine-organization', '03 Mine organization', 'Mine organization', 3),
('geotechnics', '04 Geotechnics', 'Geotechnics', 4),
('drilling', '05 Drilling', 'Drilling', 5),
('blasting', '06 Blasting', 'Blasting', 6),
('ground-support', '07 Ground support', 'Ground support', 7),
('ventilation', '08 Ventilation', 'Ventilation', 8),
('topography', '09 Topography', 'Topography', 9),
('loading-and-hauling', '10 Loading and hauling', 'Loading and hauling', 10),
('resource-estimation', '11 Resource estimation', 'Resource estimation', 11),
('economics-and-costs', '12 Economics and costs', 'Economics and costs', 12),
('reserve-calculations', '13 Reserve calculations', 'Reserve calculations', 13),
('optimization-and-design', '14 Optimization and design', 'Optimization and design', 14),
('planning', '15 Planning', 'Planning', 15),
('grade-control', '16 Grade control', 'Grade control', 16),
('finances-and-markets', '17 Finances and markets', 'Finances and markets', 17),
('performance-levels', '18 Performance levels', 'Performance levels', 18),
('data-management', '19 Data management', 'Data management', 19),
('facilities', '20 Facilities', 'Facilities', 20),
('qhse', '21 QHSE', 'QHSE', 21),
('logistics-and-purchasing', '22 Logistics and purchasing', 'Logistics and purchasing', 22),
('maintenance', '23 Maintenance', 'Maintenance', 23),
('legal-and-tax', '24 Legal and tax', 'Legal and tax', 24),
('hr-and-organization', '25 HR and organization', 'HR and organization', 25)
ON CONFLICT (slug) DO NOTHING;

-- ============================================
-- TABLA 3: languages (4 idiomas)
-- ============================================
CREATE TABLE IF NOT EXISTS public.languages (
    id SERIAL PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_languages_code ON public.languages(code);
CREATE INDEX IF NOT EXISTS idx_languages_name ON public.languages(name);

-- Insertar los 4 idiomas
INSERT INTO public.languages (code, name, display_name) VALUES
('es', 'Spanish', 'Spanish'),
('en', 'English', 'English'),
('ru', 'Russian', 'Russian'),
('fr', 'French', 'French')
ON CONFLICT (code) DO NOTHING;

-- ============================================
-- Comentarios para documentación
-- ============================================
COMMENT ON TABLE public.countries IS 'Tabla de referencia para países (reutilizable para nationality y work_country)';
COMMENT ON TABLE public.mining_topics IS 'Tabla de referencia para los 25 mining topics (reutilizable en múltiples campos)';
COMMENT ON TABLE public.languages IS 'Tabla de referencia para idiomas (reutilizable para main_language y others_languages)';

